In [13]:
import pandas as pd
import numpy as np

In [14]:
dataset = pd.read_csv("house_Data.csv")

In [15]:
dataset.shape

(21613, 11)

In [16]:
x = dataset.iloc[:, [3,4]].values
y = dataset.iloc[:, -1].values

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [18]:
x

array([[5.650e+03, 1.000e+00],
       [7.242e+03, 2.000e+00],
       [1.000e+04, 1.000e+00],
       ...,
       [1.350e+03, 2.000e+00],
       [2.388e+03, 2.000e+00],
       [1.076e+03, 2.000e+00]])

In [19]:
y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [20]:
from sklearn.linear_model import LinearRegression 
regressor = LinearRegression() 
regressor.fit(X_train, y_train)

LinearRegression()

In [21]:
y_pred = regressor.predict(X_test)

In [22]:
y_pred

array([795554.35059871, 660789.55506513, 446053.54464655, ...,
       621652.28245232, 534707.75526181, 452804.43542934])

In [11]:
from sklearn import metrics 
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_absolute_error(y_test, y_pred)))

Mean Absolute Error: 217846.7647697289
Mean Squared Error: 109993546353.38124
Root Mean Squared Error: 466.7405754482129


In [12]:
regressor.score(X_test,y_test)

0.07634359604011465