In [12]:
import pandas as pd
import numpy as np

In [13]:
dataset = pd.read_csv("User_Data.csv")
dataset.describe()

User ID         Age  EstimatedSalary  Purchased
count  1.900000e+01  19.000000        19.000000  19.000000
mean   1.567745e+07  29.526316     56947.368421   0.210526
std    7.151572e+04   8.852924     33569.949664   0.418854
min    1.557077e+07  18.000000     18000.000000   0.000000
25%    1.561188e+07  25.500000     27000.000000   0.000000
50%    1.569483e+07  27.000000     57000.000000   0.000000
75%    1.572804e+07  33.500000     80000.000000   0.000000
max    1.581094e+07  47.000000    150000.000000   1.000000

In [14]:
x = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000]], dtype=int64)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

In [16]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
xtrain = sc_x.fit_transform(X_train)
xtest = sc_x.transform(X_test)


In [17]:
from sklearn.svm import SVC 
classifier = SVC(kernel='linear', random_state=0) 
classifier.fit(xtrain, y_train)

SVC(kernel='linear', random_state=0)

In [18]:
y_pred = classifier.predict(xtest)

In [19]:
y_pred

array([0, 0, 0, 1], dtype=int64)

In [20]:
from sklearn.metrics import confusion_matrix 
cm= confusion_matrix(y_test, y_pred) 
cm

array([[3, 0],
       [0, 1]], dtype=int64)

In [21]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  1.0


In [26]:
dataset.head(9)

User ID   Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1
8  15600575    Male   25            33000          0

In [27]:
dataset.tail(9)

User ID   Gender  Age  EstimatedSalary  Purchased
10  15570769  Female   26            80000          0
11  15606274  Female   26            52000          0
12  15746139    Male   20            86000          0
13  15704987    Male   32            18000          0
14  15628972    Male   18            82000          0
15  15697686    Male   29            80000          0
16  15733883    Male   47            25000          1
17  15617482    Male   45            26000          1
18  15704583    Male   46            28000          1

In [25]:
dataset.shape

(19, 5)